### ISSUE TITLE
run test in watch mode from terminal

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#34]
Hi,

I am not a fan of `blessed` window  to observe my test results as it is tiny and scrolling is not working for me. I saw this in the code,

```
terms.forEach(function(term) {
  term.on('wheelup', term.scroll.bind(term, -1));
  term.on('wheeldown', term.scroll.bind(term, 1));
});
```

but I use  trackpad on my mac and not sure the events are same. Anyway, I prefer to see the test runs in watch mode in a separate terminal. 

`npm run test-unit` , just runs it once and quit. Can you please add support for running tests in watch mode from terminal.

something along the lines of https://github.com/prometheusresearch/react-forms/blob/2.0.0/Makefile#L20

thanks.

**Comment by vslinko** [comment]
You could run `./bin/unit_tests --watch` to run unit tests in watch mode.
But right now you can't run e2e tests in watch mode separately from test server.
I'll think about it.

**Comment by bsr203** [comment]
that's fine. It is mostly unit test I was concerned. Even if you plan to add support for e2e in watch, please consider providing a command to just run unit test as it makes it faster, and guides the development. thanks.

**Comment by vslinko** [comment]
Hello.

I'm done completely new test runner. https://github.com/vslinko/ripster/commit/6b9a62e42f0ae80b734d9db474c9d37ddfc30406
- It could check that neo4j, dev server, and selenium are runned
- It could run unit tests and e2e tests simultaneously. `./bin/run_tests`
- It could watch for build and restart all kinds of tests. `./bin/run_tests --watch`
- It could run only specific tests. `./bin/run_tests src/__tests__/unitTest.js specs/someSpec.js`

But one problem is still exists — it's pretty slow.

**Comment by bsr203** [comment]
:-) thanks. can't wait to try it out. will give feedback.

**Comment by bsr203** [comment]
HI,

running `npm run test-specs` gave following error.

note that I have some changes locally, and the source at `bundles/auth` doesn't exist in my project yet. but, it may nice not to to see the npm errors.

```
⨯ signin/validation
  not ok 2 Error: element ([data-marker="SignInForm-Form"]) still not existing after 5000ms
    ---
      operator: error
      expected: |-
        undefined
      actual: |-
        [Error: element ([data-marker="SignInForm-Form"]) still not existing after 5000ms]
      at: run (/Users/bsr/test/client/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
      stack: |-
        Error: element ([data-marker="SignInForm-Form"]) still not existing after 5000ms
            at [object Object]._onTimeout (/Users/bsr/test/client/specs/createHeadlessBrowser.js:98:16)
            at Timer.listOnTimeout (timers.js:89:15)
    ...

# tests 2
# pass  0
⨯ fail  2

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-specs"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! client@1.0.0 test-specs: `./bin/run_tests specs | faucet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@1.0.0 test-specs script './bin/run_tests specs | faucet'.
npm ERR! This is most likely a problem with the client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/run_tests specs | faucet
npm ERR! You can get their info via:
npm ERR!     npm owner ls client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bsr/test/client/npm-debug.log
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-specs' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'pretest-specs', 'test-specs', 'posttest-specs' ]
5 info pretest-specs client@1.0.0
6 info test-specs client@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info client@1.0.0 Failed to exec test-specs script
9 verbose stack Error: client@1.0.0 test-specs: `./bin/run_tests specs | faucet`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid client@1.0.0
11 verbose cwd /Users/bsr/test/client
12 error Darwin 13.4.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-specs"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error client@1.0.0 test-specs: `./bin/run_tests specs | faucet`
17 error Exit status 1
18 error Failed at the client@1.0.0 test-specs script './bin/run_tests specs | faucet'.
18 error This is most likely a problem with the client package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./bin/run_tests specs | faucet
18 error You can get their info via:
18 error     npm owner ls client
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

otherwise, it works great and love how easy to start everything through startup scripts. thanks again for your effort.

**Comment by vslinko** [comment]
Hmm. If you deleted `SignInForm` you also should delete `specs/signin` to remove this errors.
